/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject2;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

    Rest_display rd;
    String s;
    String phone;
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    int count=0;
    ArrayList<String> items = new ArrayList<String>();
    ArrayList<Integer> qty = new ArrayList<Integer>();
    public Menu(){}
    /**
     * Creates new form Menu
     */
    public Menu(Rest_display rd,String s,String phone) {
        this.rd = rd;
        this.s = s;
        this.phone = phone;
        initComponents();
        try{
Class.forName("oracle.jdbc.OracleDriver");
//JOptionPane.showMessageDialog(this,"Driver Loaded!");
try {
con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl",
        "c##deepak","barca10118");
//JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
}
catch (SQLException ex) {
Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}
catch(ClassNotFoundException ex){
Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());

} 
        updateCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Veg/NV", "Rating", "Price", "Select", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Delivery Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          int count=0;
          for(int i=0;i<jTable1.getRowCount();i++)
          {
              if(jTable1.getModel().getValueAt(i,4)==null)
              {
                  continue;
              }
              else if((Boolean)jTable1.getModel().getValueAt(i,4))
              {
                  items.add((String)jTable1.getModel().getValueAt(i,0));
                  qty.add((Integer)jTable1.getModel().getValueAt(i,5));
//JOptionPane.showMessageDialog(this,jTable1.getModel().getValueAt(i,0));  
              }
          }
          /*Iterator itr = items.iterator();
          Iterator itr1 = qty.iterator();
          while(itr.hasNext() && itr1.hasNext())
          {
              JOptionPane.showMessageDialog(this,itr.next());
              JOptionPane.showMessageDialog(this,itr1.next());
          }*/
          try
          {
              //con.setAutoCommit(true);
              String sql1 = "SELECT CONCAT('O', SUBSTR(CONCAT('00000', CAST(COUNT(*)+1 AS VARCHAR2(10))), -5)) AS temp FROM ORDERS_LIST";
              ps = con.prepareStatement(sql1);
              rs = ps.executeQuery();
              rs.next();
              String order_id = rs.getString("temp");
               //JOptionPane.showMessageDialog(this,order_id);
              String sql = "select rest_id from restaurants1 where rest_name like ?";
              ps = con.prepareStatement(sql);
              ps.setString(1,s);
              rs = ps.executeQuery();
              rs.next();
              String rest_id = rs.getString("rest_id");
              //JOptionPane.showMessageDialog(this,rest_id);
              String emp_id = null;
              String sql2 = "select user_id from users where phone like ?";
              ps = con.prepareStatement(sql2);
              ps.setString(1,phone);
              rs = ps.executeQuery();
              rs.next();
              String user_id = rs.getString("user_id");
              //JOptionPane.showMessageDialog(this,user_id);
              String user_add = (String)jComboBox1.getSelectedItem();
              //JOptionPane.showMessageDialog(this,user_add);
              String sql4 = "insert into orders_list values(?,?,NULL,?,systimestamp,NULL,?)";
              ps = con.prepareStatement(sql4);
              ps.setString(1,order_id);
              ps.setString(2,rest_id);
              ps.setString(3,user_id);
              ps.setString(4,user_add);
              rs = ps.executeQuery();
              Iterator itr = items.iterator();
              Iterator itr1 = qty.iterator();
              while(itr.hasNext() && itr1.hasNext())
              {
                  sql = "insert into order_details values(?,?,?)";
                  ps = con.prepareStatement(sql);
                  ps.setString(1,order_id);
                  ps.setString(2,(String)itr.next());
                  ps.setInt(3,((Integer)itr1.next()).intValue());
                  ps.executeQuery();
              }
              //JOptionPane.showMessageDialog(this,"Order has been placed successfully");
              Confirm_orders co = new Confirm_orders(rest_id,order_id);
              co.show();
              this.setVisible(false);
              
              
          }
          catch(Exception e)
          {
               JOptionPane.showMessageDialog(this,e.getMessage());
          }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        if(count==0)
        {
        try
        {
           
            String sql = "select menu1.item_name,menu2.veg,menu1.rating,menu1.price from menu1,menu2,restaurants1 where menu1.item_name = menu2.item_name and menu1.rest_id = restaurants1.rest_id and restaurants1.rest_name = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1,s);
            rs = ps.executeQuery();
            
             //tblMode2.setRowCount(0);
            while(rs.next())
            {
          
                String item_name = rs.getString("item_name");
                String veg = rs.getString("veg");
                String rating = String.valueOf(rs.getString("rating"));
                String price = String.valueOf(rs.getString("price"));
                Object tbData[] = {item_name,veg,rating,price,false,1};
                DefaultTableModel tblMode2 = (DefaultTableModel)jTable1.getModel();
                tblMode2.addRow(tbData);
            }
            count++;
        }
        catch(Exception e){ JOptionPane.showMessageDialog(this,e.getMessage());}
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            rd.setVisible(true);
            dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
     private void updateCombo()
    {
        
        
        try
        {
            
            String sql = "select user_add from address,users where users.user_id = address.user_id and phone like ?";
            ps = con.prepareStatement(sql);
            ps.setString(1,phone);
            rs = ps.executeQuery();
            while(rs.next())
            {
             
                jComboBox1.addItem(rs.getString("user_add"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
